travis:
  secure:
    BINSTAR_TOKEN: ZzI2zL7kGmb9JN9/VdIbddwHVVH16Womg8460Zh/Fbcn9MKDc+AipTAlOPQ9YYOHZr4OCxX5IzQXc3/hFkIl0MzNzKIqo8SoYS/IgHG4iCQqOH/9Nr0izJRHf9Nt/NgbNwR/vhykejFIFnOoc0IzCZ8sVJd29UE4ReekNt4CLog0xcac02QblikASP0AvTYd5aE8PIevKiZhCi+14qHKTBS7KGJtAf+fsOkdWDdwVF2bN6KcUR1BkYUJTP9smXAZWS6eUhUXYMMOqjz+SLgsEz8U5t5OxwyGYdIVnwDHm0JI+Z4gMO/XbseNUCa5nzk4ebUW/ULlHq7wi5b7E1zB6DSxwR6Ha6hMNntQe2+4stqnT8tIqdgKEHiCA4z9ROriZLMNWlwYZImoLiFysmCp6BNHqd6oEGIxUR8jmEEKBc0zHeRluD+ax2M5/FL0CkGtFzW5+30+Q5Kb96q9APJyLhRKe6Fmh/kquZa5zIbzp/oFS5GzqkG0MKJ1NUPWb/0n2g7iFezLP1lyI3xYCGmhHgxRzDN9s2LR9KgIzb9IOAfn5fD9JnwAbQ4l6alqwlT4ChLoa3GTsTnpuZ5ZwMvTIaNwYnqGQPKvHk3Vuq8ScV2v28g8G7H/gdh5zozZAZdF2DH4/1AJYKdbFao25ICZU0FQM/EJhxQoxFZLXESvRE0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
